import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-test-errors',
  templateUrl: './test-errors.component.html',
  styleUrls: ['./test-errors.component.css']
})
export class TestErrorsComponent implements OnInit {
  baseUrl = 'https://localhost:5001/api/'
  validationErrors: string[] = [];

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
  }

  get404Error() {
    this.http.get(this.baseUrl + 'buggy/not-found').subscribe(response => {
      console.log(response);
    }, error => {
      console.log(error);
    })
  }

  get400Error() {
    this.http.get(this.baseUrl + 'buggy/bad-request').subscribe(response => {
      console.log(response);
    }, error => {
      console.log(error);
    })
  }

  get500Error() {
    this.http.get(this.baseUrl + 'buggy/server-error').subscribe(response => {
      console.log(response);
    }, error => {
      console.log(error);
    })
  }

  get401Error() {
    this.http.get(this.baseUrl + 'buggy/auth').subscribe(response => {
      console.log(response);
    }, error => {
      console.log(error);
    })
  }

  get400ValidationError() {
    this.http.post(this.baseUrl + 'account/register', {}).subscribe(response => {
      console.log(response);
    }, error => {
      console.log(error);
      this.validationErrors = error;
    })
  }
}

// ............................................................
// .......................................'....................
// ...................................''''................'''..
// ..............................,'',,,',,;::,''''',',,'.',,,..
// .............................cko::lodlcodOOl,,;;,''.........
// ...........................':x0KKKXX0;';'dXO;';;,...........
// .........................,xOxc;cxKXXKo;,:OXd,,;;,'..........
// .........................:0X0c..'kXXXXKd::cll;,,;,..........
// .........................,OXX0kdd0XXXXkccccdKk:,,;'.........
// ..........................c0XXXXXXXXXXx;';xXNXOc,,,.........
// ...........................:kXXXXXXXXXX0dd0XXXX0l,,,........
// ............................'ok0XXXXXXXXXXXXXXXX0c,,........
// ...............................;kXXXXXXXXXXXXXXXXO:''.......
// .....'lxxdolc:'.................'dKNXXXXXXXXXXXXXXk;'.......
// ..,lxxOXXNXXXX0ko;................oKXXXXXXXXXXXXXXXo,.......
// ...;OXXXXXXXXXXXXKkc..............'xXXXXXXXXXXXXXXX0:.......
// ....:xKXXXXXXXXK0000x;.............:0XXXXXXXXXXXXXXXd'......
// ......l0XXKOdlc:;;;:c:.............'xXXXXXXXXXXXXXXX0:......
// .......d0xc,,,,,,,,,,'............,lOXXXXXXXXXXXXXXXXd......
// .......,:,,,,,;cloodolc'..........:xKK0XXXXXXXXXXXXXXk,.....
// .........,,,cxOXXNXK00Ox;..... ..,',oO0XXXXXXXXXXXK0XXx,....
// ........',ckKXX0xol::;;;,..... ....cOXXXXXXXXXXXXX0xdlc,....
// ........'l0XXOo:,,,,;,,,,,,'.......:OXNXXXXXXXXXXXXd'''.....
// ........cKXKd;,,,,,,;coxkko:'...''',;d0XXXXXXXXXXXXO:.......
// .......'xNKo,,,,,,;lOKXXkc,,,,,okc',,,:lxk0KKKK0Oxo:,'......
// ........dXd,,;;,,:kXXXKo,,,,,lOKXk:',,,,,,;::::;;,,,,,......
// ........:xc';,;';kXXXKo,,;;':OXXXXOl,,,;;;;;;;,,,;;,,;:.....
// .........,,';;,'cKXXXk;';;;':0NXXXXKko:;,,,,,,,,,,;cd0k,....
// ............,;,'lKXXXx,,;,;,;xXXXXXXXXKOxdoooooodk0XXXd.....
// .............',';OXXXO:',;;,,;lxKXNXXXXXXXXXKKKKKKKKKx,.....
// .................cOXXXx;,,;,,,',cx0KKKK00OOOkkkkkkkxc.......
// ..................,oO0Od;'''''''..,:lodxxkkkkkkxdo:'........
// ....................,ldxd;............',,;;:;;;,'...........
// ......................',;;;ldc,;:'.............';;lo'.......
// ..........................'cl;';c'. ...........':;,c'.......
